trigger:
  - main

resources:
  - repo: self

variables:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build and Push Docker Image Stage
    jobs:
      - job: Build
        displayName: 'Build job'
        pool:
          vmImage: $(vmImage)
        steps:
          - task: Docker@2
            displayName: Build and Push Image To Docker Hub
            inputs:
              command: buildAndPush
              repository: 'leonardomm26/backend'
              dockerfile: '**/Dockerfile'
              containerRegistry: 'Docker Hub'
              tags: |
                latest
                $(Build.BuildId)  